apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-api-sa
  namespace: payments
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-client-sa
  namespace: payments
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: attacker-sa
  namespace: attacker
automountServiceAccountToken: true
