apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api

  template:
    metadata:
      labels:
        app: payments-api
        security-profile: web-api

    spec:
      serviceAccountName: payments-api-sa
      automountServiceAccountToken: false

      containers:
        - name: app
          image: nginxinc/nginx-unprivileged:stable-alpine

          ports:
            - containerPort: 8080

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          volumeMounts:
            - name: nginx-cache
              mountPath: /tmp

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi

      volumes:
        - name: nginx-cache
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: payments-api
  namespace: payments

spec:
  selector:
    app: payments-api

  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

  type: ClusterIP