apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: lab-trace-shell-exec
spec:
  kprobes:
    - call: "security_bprm_check"
      syscall: false
      args:
        - index: 0
          type: "linux_binprm"
      selectors:
        - matchBinaries:
            - operator: "In"
              values:
                - "/bin/sh"
                - "/bin/bash"
                - "/usr/bin/curl"
                - "/usr/bin/wget"
                - "/bin/nc"
                - "/usr/bin/nc"
          matchActions:
            - action: Post
