apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: lab-trace-serviceaccount-token-access
spec:
  kprobes:
    - call: "security_file_open"
      syscall: false
      args:
        - index: 0
          type: "file"
      selectors:
        - matchArgs:
            - index: 0
              operator: "Prefix"
              values:
                - "/var/run/secrets/kubernetes.io/serviceaccount/token"
                - "/run/secrets/kubernetes.io/serviceaccount/token"
          matchActions:
            - action: Post
