apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-pod
  namespace: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure-pod

  template:
    metadata:
      labels:
        app: insecure-pod
        security-profile: web-api

    spec:
      serviceAccountName: payments-api-sa
   

      containers:
        - name: app
          image: nginx:latest

          ports:
            - containerPort: 8080

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          volumeMounts:
            - name: nginx-cache
              mountPath: /tmp

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi

      volumes:
        - name: nginx-cache
          emptyDir: {}
