apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - logstash-config.yaml
  - logstash-deployment.yaml
  - logstash-service.yaml
  - filebeat-rbac.yaml
  - filebeat-config.yaml
  - filebeat-daemonset.yaml
