apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.17.0
          ports:
            - containerPort: 5044
              name: beats
            - containerPort: 9600
              name: http
          env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quickstart-es-elastic-user
                  key: elastic
          volumeMounts:
            - name: config
              mountPath: /usr/share/logstash/pipeline/runtime-security.conf
              subPath: runtime-security.conf
            - name: config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
          resources:
            requests:
              cpu: 250m
              memory: 768Mi
            limits:
              cpu: "1"
              memory: 1536Mi
      volumes:
        - name: config
          configMap:
            name: logstash-pipeline
